"""empty message

Revision ID: 22a4553bd543
Revises: 5f3d70ba9a72
Create Date: 2025-03-05 15:16:57.161840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a4553bd543'
down_revision = '5f3d70ba9a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('done',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('done',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
