"""empty message

Revision ID: 5f3d70ba9a72
Revises: 63d39808b335
Create Date: 2025-03-04 01:38:45.341579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3d70ba9a72'
down_revision = '63d39808b335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('topId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_todo_topid', 'topic', ['topId'], ['topId'])

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pid', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_topic_pid', 'people', ['pid'], ['pid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint('fk_topic_pid', type_='foreignkey')
        batch_op.drop_column('pid')

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_todo_topid', type_='foreignkey')
        batch_op.alter_column('topId',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
