"""empty message

Revision ID: 63d39808b335
Revises: 94aafddd4804
Create Date: 2025-03-03 23:11:46.455434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d39808b335'
down_revision = '94aafddd4804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('topId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('topId')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('lastName', sa.String(), nullable=False))
        batch_op.drop_column('age')
        batch_op.drop_column('job')

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topId', sa.Integer(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('topId')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('lastName')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    op.drop_table('topic')
    # ### end Alembic commands ###
