"""CASCADES

Revision ID: 760d4120c056
Revises: 22a4553bd543
Create Date: 2025-03-06 13:02:39.406852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760d4120c056'
down_revision = '22a4553bd543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_todo_topid', type_='foreignkey')
        batch_op.create_foreign_key('fk_todo_topid', 'topic', ['topId'], ['topId'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint('fk_topic_pid', type_='foreignkey')
        batch_op.create_foreign_key('fk_topic_pid', 'people', ['pid'], ['pid'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint('fk_topic_pid', type_='foreignkey')
        batch_op.create_foreign_key('fk_topic_pid', 'people', ['pid'], ['pid'])

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_todo_topid', type_='foreignkey')
        batch_op.create_foreign_key('fk_todo_topid', 'topic', ['topId'], ['topId'])

    # ### end Alembic commands ###
